name: gridgen compiler checks
on:
  # run at 6 AM UTC every day
  schedule:
    - cron: '0 6 * * *' 
  push:
  pull_request:
    branches:
      - main
      - develop
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  PIXI_BETA_WARNING_OFF: true
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # test latest gcc
          - {os: ubuntu-latest, compiler: gcc, version: 13, release: false}
          - {os: macos-14, compiler: gcc, version: 13, release: true}
          - {os: windows-latest, compiler: gcc, version: 13, release: false}
          # test intel-classic
          - {os: ubuntu-22.04, compiler: intel-classic, version: 2021.7, release: false}
          - {os: macos-13, compiler: intel-classic, version: 2021.7, release: true}
          # test previous gcc
          - {os: ubuntu-latest, compiler: gcc, version: 12, release: false}
          - {os: ubuntu-latest, compiler: gcc, version: 11, release: false}
          # test ifx
          - {os: ubuntu-22.04, compiler: intel, version: "2025.0", release: true}
          - {os: windows-2022, compiler: intel, version: "2025.0", release: true}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout gridgen
        uses: actions/checkout@v5
        with:
          path: gridgen

      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ (runner.os == 'macOS') && (matrix.compiler == 'intel-classic') }}
        with:
          xcode-version: "14.3.1"

      - name: Setup ${{ matrix.compiler }} ${{ matrix.version }} on ${{ matrix.os }}
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: ${{ matrix.compiler}}
          version: ${{ matrix.version }}
          
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.14
        with:
          pixi-version: v0.41.4
          manifest-path: "gridgen/pixi.toml"

      - name: Build gridgen
        working-directory: gridgen
        run: |
          pixi run setup
          pixi run build

      - name: Show build log
        if: failure()
        working-directory: gridgen
        run: cat builddir/meson-logs/meson-log.txt
      
      - name: Upload build log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: meson-log.txt
          path: gridgen/builddir/meson-logs/meson-log.txt
    
      - name: Unit test gridgen
        if: success()
        working-directory: gridgen
        run: |
          pixi run test-initial
          pixi run test-write
          pixi run test-shapefile
          pixi run test-intersect
          pixi run test-vtk

      - name: Get OS tag
        if: ${{ matrix.release == 'true' }}
        id: ostag
        run: |
          ostag=$(python -c "from modflow_devtools.ostags import get_ostag; print(get_ostag())")
          echo "ostag=$ostag" >> $GITHUB_OUTPUT

      # Build your artifact here (e.g., compile code, package files)
      - name: Build Artifact
        if: ${{ matrix.release == 'true' }}
        run: |
          echo "Building $ostag.zip..."
          zip -r $ostag.zip bin/

      - name: Upload Release Asset
        if: ${{ matrix.release == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          files: $ostag.zip # Path to your artifact
          overwrite: true # Set to true to replace an existing artifact with the same name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}